# Generated by Django 4.2.15 on 2024-08-20 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imgapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imgapp',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='imgapp',
            name='time',
            field=models.TimeField(auto_now=True),
        ),
    ]
