# Generated by Django 4.2.15 on 2024-08-22 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imgapp', '0002_imgapp_date_imgapp_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='imgapp',
            name='slug',
            field=models.SlugField(blank=True, max_length=255),
        ),
    ]
