# Generated by Django 4.2.15 on 2024-08-20 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imgapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imgapp',
            name='image',
            field=models.URLField(editable=False),
        ),
    ]
